import { describe, expect, it, vi } from "vitest";
import { createSfhsPixiCanvasCompatContext } from "./context.ts";
import { Container, Texture } from "pixi.js";
import { createSfhsCompatTextureRegistry, createSfhsDrawImagePresenter, presentSfhsDrawImage, resolveSfhsDrawImage, SfhsCanvasSourceRegistryError, type SfhsResolvedDrawImage } from "./texture-registry.ts";

const canvas = (connected = false) => ({ nodeName: "CANVAS", isConnected: connected, width: 32, height: 16 }) as unknown as HTMLCanvasElement;
const texture = () => ({ width: 32, height: 16, source: { update: vi.fn() }, destroy: vi.fn() });
const metadata = (updatePolicy: "static" | "explicit-dirty" = "static") => ({ owner: "fixture", purpose: "generated-marker", origin: "generated" as const, updatePolicy, expectedWidth: 32, expectedHeight: 16 });

describe("attributed Canvas source texture registry", () => {
  it("registers a disconnected static Canvas once, reuses it, and releases it deterministically", () => {
    const created = texture(); const factory = vi.fn(() => created); const registry = createSfhsCompatTextureRegistry({ textureFrom: factory as never }); const source = canvas(); const first = registry.registerCanvasSource(source, metadata()); const second = registry.registerCanvasSource(source, metadata());
    expect(first.id).toBe(second.id); expect(registry.resolve(first)).toBe(created); expect(registry.resolve(second)).toBe(created); expect(factory).toHaveBeenCalledTimes(1); expect(registry.getDiagnostics()).toMatchObject({ textureUploads: 1, cacheHits: 1, registeredSourceCount: 1 }); registry.release(first); expect(created.destroy).not.toHaveBeenCalled(); registry.release(second); expect(created.destroy).toHaveBeenCalledWith(true); expect(registry.getDiagnostics().destroyedTextureCount).toBe(1);
  });
  it("refreshes explicit-dirty exactly once and blocks static mutation", () => {
    const created = texture(); const registry = createSfhsCompatTextureRegistry({ textureFrom: (() => created) as never }); const dirty = registry.registerCanvasSource(canvas(), metadata("explicit-dirty")); registry.resolve(dirty); registry.markDirty(dirty); registry.resolve(dirty); registry.resolve(dirty); expect(created.source.update).toHaveBeenCalledTimes(1); expect(registry.getDiagnostics()).toMatchObject({ textureRefreshes: 1, cacheHits: 1 }); const staticRef = registry.registerCanvasSource(canvas(), { ...metadata(), owner: "static" }); expect(() => registry.markDirty(staticRef)).toThrow(SfhsCanvasSourceRegistryError);
  });
  it("rejects visible, unknown, and conflicting-attribution sources", () => {
    const registry = createSfhsCompatTextureRegistry({ textureFrom: (() => texture()) as never }); expect(() => registry.registerCanvasSource(canvas(true), metadata())).toThrow(/Connected Canvas/); expect(() => registry.registerCanvasSource({ nodeName: "IMG", width: 32, height: 16 } as unknown as HTMLCanvasElement, metadata())).toThrow(SfhsCanvasSourceRegistryError); const source = canvas(); registry.registerCanvasSource(source, metadata()); expect(() => registry.registerCanvasSource(source, { ...metadata(), owner: "other" })).toThrow(SfhsCanvasSourceRegistryError); expect(registry.getDiagnostics()).toMatchObject({ visibleSourceRejections: 1 });
  });
  it("resolves cropped drawImage commands with the B4A frozen transform, alpha, composite, and smoothing state", () => {
    const created = texture(); const nearest = texture(); const registry = createSfhsCompatTextureRegistry({ textureFrom: (() => created) as never, variantFrom: (() => nearest) as never }); const ref = registry.registerCanvasSource(canvas(), metadata()); const context = createSfhsPixiCanvasCompatContext(); context.beginFrame(); context.save(); context.translate(7, 3); context.rotate(Math.PI / 2); context.setGlobalAlpha(.4); context.setCompositeOperation("multiply"); context.setImageSmoothingEnabled(false); context.drawImage(ref, 1, 2, 3, 4, 10, 20, 30, 40); const resolved = resolveSfhsDrawImage(context.getCommands().at(-1)!, registry);
    expect(resolved.texture).toBe(nearest); expect(resolved.source).toEqual([1, 2, 3, 4]); expect(resolved.destination).toEqual([10, 20, 30, 40]); expect(resolved.state.globalAlpha).toBe(.4); expect(resolved.state.globalCompositeOperation).toBe("multiply"); expect(resolved.state.imageSmoothingEnabled).toBe(false); expect(resolved.state.transform[4]).toBe(7); expect(resolved.state.transform[5]).toBe(3); expect(Object.isFrozen(resolved.state)).toBe(true);
  });
  it("cleans up only the requested owner and never destroys borrowed Pixi textures", () => {
    const first = texture(); const second = texture(); const borrowedTexture = texture(); const registry = createSfhsCompatTextureRegistry({ textureFrom: vi.fn().mockReturnValueOnce(first).mockReturnValueOnce(second) as never }); const owner = registry.registerCanvasSource(canvas(), metadata()); const other = registry.registerCanvasSource(canvas(), { ...metadata(), owner: "other" }); const borrowed = registry.registerTexture("atlas", borrowedTexture as never, { owner: "borrower", purpose: "atlas", origin: "embedded", updatePolicy: "static" }); registry.resolve(owner); registry.resolve(other); registry.destroyOwner("fixture"); expect(first.destroy).toHaveBeenCalledWith(true); expect(second.destroy).not.toHaveBeenCalled(); registry.destroy(); expect(borrowedTexture.destroy).not.toHaveBeenCalled(); expect(registry.getDiagnostics().borrowedTextureCount).toBe(1); expect(borrowed.id).toBe("borrowed:atlas");
  });
  it("owns independent nearest and linear variants, invalidates them on dirty refresh, and destroys them on cleanup", () => {
    const base = texture(); const nearest = texture(); const linear = texture(); const nextNearest = texture(); const variants = vi.fn().mockReturnValueOnce(nearest).mockReturnValueOnce(linear).mockReturnValueOnce(nextNearest); const registry = createSfhsCompatTextureRegistry({ textureFrom: (() => base) as never, variantFrom: variants as never }); const ref = registry.registerCanvasSource(canvas(), metadata("explicit-dirty"));
    expect(registry.resolveVariant(ref, "nearest")).toBe(nearest); expect(registry.resolveVariant(ref, "linear")).toBe(linear); expect(nearest).not.toBe(linear); expect(registry.resolveVariant(ref, "nearest")).toBe(nearest); expect(variants.mock.calls.map((call) => call[1])).toEqual(["nearest", "linear"]); expect(variants.mock.calls.every((call) => call[0] === base)).toBe(true); registry.markDirty(ref); registry.resolve(ref); expect(nearest.destroy).toHaveBeenCalledWith(true); expect(linear.destroy).toHaveBeenCalledWith(true); expect(registry.resolveVariant(ref, "nearest")).toBe(nextNearest); registry.release(ref); expect(nextNearest.destroy).toHaveBeenCalledWith(true); expect(registry.getDiagnostics()).toMatchObject({ samplingVariantsCreated: 3, samplingVariantsReused: 1, samplingVariantsInvalidated: 2, samplingVariantsDestroyed: 3 });
  });
  it("matches Canvas drawImage no-op and out-of-bounds source clipping geometry", () => {
    const created = texture(); const registry = createSfhsCompatTextureRegistry({ textureFrom: (() => created) as never, variantFrom: ((base: never) => base) as never }); const ref = registry.registerCanvasSource(canvas(), metadata()); const context = createSfhsPixiCanvasCompatContext();
    context.beginFrame(); context.drawImage(ref, -8, 2, 16, 8, 0, 0, 32, 16); const clipped = resolveSfhsDrawImage(context.getCommands().at(-1)!, registry);
    expect(clipped.isNoOp).toBe(false); expect(clipped.source).toEqual([0, 2, 8, 8]); expect(clipped.destination).toEqual([16, 0, 16, 16]);
    context.beginFrame(); context.drawImage(ref, 0, 0, 0, 8, 0, 0, 32, 16); const zero = resolveSfhsDrawImage(context.getCommands().at(-1)!, registry);
    expect(zero.isNoOp).toBe(true); expect(zero.destination).toEqual([0, 0, 32, 16]);
    context.beginFrame(); context.drawImage(ref, 99, 0, 2, 2, 0, 0, 8, 8); const outside = resolveSfhsDrawImage(context.getCommands().at(-1)!, registry);
    expect(outside.isNoOp).toBe(true);
  });
  it("owns cached cropped presentation textures through an explicit presenter", () => {
    const image = { texture: Texture.WHITE, sourceId: "fixture", sourceGeneration: 0, source: [0, 0, 1, 1], destination: [2, 3, 4, 5], isNoOp: false, state: { transform: [1, 0, 0, 1, 0, 0], globalAlpha: 1, globalCompositeOperation: "source-over", fillStyle: "#000", strokeStyle: "#000", lineWidth: 1, lineCap: "butt", font: "10px sans-serif", textAlign: "start", textBaseline: "alphabetic", imageSmoothingEnabled: true, clips: [], clipRefs: [] } } as unknown as SfhsResolvedDrawImage;
    expect(() => presentSfhsDrawImage(new Container(), image)).toThrow(SfhsCanvasSourceRegistryError); const presenter = createSfhsDrawImagePresenter(); presenter.present(new Container(), image); presenter.present(new Container(), image); expect(presenter.getDiagnostics()).toEqual({ croppedTexturesCreated: 1, croppedTexturesReused: 1, croppedTexturesDestroyed: 0 }); presenter.present(new Container(), { ...image, sourceGeneration: 1 }); expect(presenter.getDiagnostics()).toEqual({ croppedTexturesCreated: 2, croppedTexturesReused: 1, croppedTexturesDestroyed: 1 }); presenter.destroy(); expect(presenter.getDiagnostics().croppedTexturesDestroyed).toBe(2);
  });
});
