import { Application, Container, Graphics, Rectangle, Sprite, Texture } from "pixi.js";
import { createSfhsCompatClipPresenter, createSfhsCompatTextureRegistry, createSfhsPixiCanvasAssetCompat, createSfhsPixiCanvasCompatContext, createSfhsPixiCanvasCompatDiagnostics, createSfhsPixiCanvasGeometryCompat, presentSfhsDrawImage, presentSfhsGradientRect, presentSfhsGradientShape, presentSfhsText, resolveSfhsDrawImage } from "@sfhs/pixi-canvas-compat";

const host = document.querySelector<HTMLElement>("#geometry-host");
if (host === null) throw new Error("Missing geometry fixture host.");
const fixtureHost: HTMLElement = host;

async function boot(): Promise<void> {
  const application = new Application();
  await application.init({ width: 320, height: 180, autoDensity: true, autoStart: false, sharedTicker: false, preference: "webgl", preferWebGLVersion: 2, backgroundColor: 0x08111f });
  const layer = new Container({ label: "compatGeometryLayer" });
  application.stage.addChild(layer);
  fixtureHost.replaceChildren(application.canvas);
  const compat = createSfhsPixiCanvasGeometryCompat({ layer });
  const assets = createSfhsPixiCanvasAssetCompat({ layer });
  const compatibilityDiagnostics = createSfhsPixiCanvasCompatDiagnostics();
  compat.beginFrame();
  compat.setFillStyle("#22d3ee"); compat.setGlobalAlpha(0.85); compat.beginPath(); compat.arc(80, 92, 42, 0, Math.PI * 2); compat.fill();
  compat.save(); compat.translate(160, 88); compat.rotate(Math.PI / 8); compat.setStrokeStyle("#f8fafc"); compat.setLineWidth(6); compat.setLineCap("round"); compat.beginPath(); compat.moveTo(-45, -20); compat.quadraticCurveTo(0, -60, 48, 18); compat.stroke(); compat.restore();
  compat.setFillStyle("#fbbf24"); compat.ellipse(250, 92, 24, 40, 0, 0, Math.PI * 2); compat.fill();
  compat.present(); application.render();
  assets.registerTexture("white", Texture.WHITE); assets.beginFrame(); assets.setImageSmoothing("disabled"); assets.setCompositeOperation("multiply"); assets.drawImage("white", 292, 14, 14, 14);
  const gradient = assets.createLinearGradient(12, 14, 130, 14, [{ offset: 0, color: "#22d3ee" }, { offset: 1, color: "#8b5cf6" }]); assets.fillGradientRect(gradient, 12, 14, 118, 12);
  assets.setFont("700 16px system-ui"); assets.setTextAlign("center"); assets.fillText("PIXI", 160, 148, "#ffffff"); application.render();
  const generated = document.createElement("canvas"); generated.width = 8; generated.height = 8; const generatedContext = generated.getContext("2d"); if (generatedContext === null) throw new Error("Fixture needs an off-DOM Canvas source."); generatedContext.fillStyle = "#f472b6"; generatedContext.fillRect(0, 0, 8, 8);
  const registry = createSfhsCompatTextureRegistry(); const textureRef = registry.registerCanvasSource(generated, { owner: "generic-fixture", purpose: "generated-marker", origin: "generated", updatePolicy: "static", expectedWidth: 8, expectedHeight: 8 }); const linearFirst = registry.resolveVariant(textureRef, "linear"); const nearestFirst = registry.resolveVariant(textureRef, "nearest"); const unified = createSfhsPixiCanvasCompatContext(); unified.beginFrame(); unified.save(); unified.translate(272, 135); unified.rotate(Math.PI / 10); unified.setGlobalAlpha(.7); unified.setCompositeOperation("multiply"); unified.setImageSmoothingEnabled(false); unified.drawImage(textureRef, 0, 0, 20, 20); const nearest = resolveSfhsDrawImage(unified.getCommands().at(-1)!, registry); presentSfhsDrawImage(layer, nearest); const radial = assets.createRadialGradient(0, 0, 0, 0, 0, 12, [{ offset: 0, color: "#ffffff" }, { offset: 1, color: "#22d3ee" }]); const gradientCircle = presentSfhsGradientShape(layer, unified.getCommands().at(-1)!.state, radial, { kind: "circle", x: 0, y: 0, radius: 12 }); const gradientEllipse = presentSfhsGradientShape(layer, unified.getCommands().at(-1)!.state, radial, { kind: "ellipse", x: -26, y: 0, radiusX: 12, radiusY: 6, rotation: Math.PI / 5 }); const gradientProbeContext = createSfhsPixiCanvasCompatContext(); gradientProbeContext.beginFrame(); gradientProbeContext.translate(210, 38); gradientProbeContext.fillRect(0, 0, 1, 1); const gradientProbe = presentSfhsGradientShape(layer, gradientProbeContext.getCommands().at(-1)!.state, radial, { kind: "circle", x: 0, y: 0, radius: 12 }); unified.restore(); unified.setImageSmoothingEnabled(true); unified.drawImage(textureRef, 292, 135, 20, 20); const linear = resolveSfhsDrawImage(unified.getCommands().at(-1)!, registry); presentSfhsDrawImage(layer, linear); application.render();
  const assetAllocation = Object.freeze({ sprites: assets.getDiagnostics().spritesAllocated, text: assets.getDiagnostics().textAllocated, spriteCapacity: assets.getDiagnostics().spriteCapacity, textCapacity: assets.getDiagnostics().textCapacity });
  for (let frame = 0; frame < 8; frame += 1) {
    assets.beginFrame(); assets.drawImage("white", 292, 14, 14, 14); assets.fillText(`F${frame}`, 160, 148, "#ffffff"); application.render();
  }
  const assetLifecycle = Object.freeze({ frames: 8, allocationsStable: assets.getDiagnostics().spritesAllocated === assetAllocation.sprites && assets.getDiagnostics().textAllocated === assetAllocation.text, capacitiesStable: assets.getDiagnostics().spriteCapacity === assetAllocation.spriteCapacity && assets.getDiagnostics().textCapacity === assetAllocation.textCapacity, diagnostics: assets.getDiagnostics() });
  compatibilityDiagnostics.recordFrame({ commands: compat.getCommands(), geometry: compat.getDiagnostics(), assets: assets.getDiagnostics(), presentationMilliseconds: 1, activeLayers: 1 });
  const checker = (container: Container, texture: Texture, x: number) => { const sprite = container.addChild(new Sprite(texture)); sprite.position.set(x, 0); sprite.width = 20; sprite.height = 20; };
  const normalOrder = new Container(); checker(normalOrder, nearest.texture, 0); checker(normalOrder, linear.texture, 24); const reversedOrder = new Container(); checker(reversedOrder, linear.texture, 24); checker(reversedOrder, nearest.texture, 0); application.stage.addChild(normalOrder, reversedOrder); const digest = (target: Container) => Array.from(application.renderer.extract.pixels(target).pixels).reduce((total, value) => (total * 31 + value) >>> 0, 7); const orderIndependent = digest(normalOrder) === digest(reversedOrder); normalOrder.destroy({ children: true }); reversedOrder.destroy({ children: true });
  const dirtySource = document.createElement("canvas"); dirtySource.width = 2; dirtySource.height = 2; dirtySource.getContext("2d")?.fillRect(0, 0, 2, 2); const dirtyRegistry = createSfhsCompatTextureRegistry(); const dirtyRef = dirtyRegistry.registerCanvasSource(dirtySource, { owner: "generic-fixture", purpose: "dirty-marker", origin: "generated", updatePolicy: "explicit-dirty", expectedWidth: 2, expectedHeight: 2 }); const beforeDirtyNearest = dirtyRegistry.resolveVariant(dirtyRef, "nearest"); const beforeDirtyLinear = dirtyRegistry.resolveVariant(dirtyRef, "linear"); dirtySource.getContext("2d")?.clearRect(0, 0, 2, 2); dirtyRegistry.markDirty(dirtyRef); const afterDirtyNearest = dirtyRegistry.resolveVariant(dirtyRef, "nearest"); const afterDirtyLinear = dirtyRegistry.resolveVariant(dirtyRef, "linear"); const dirtyRefreshIndependent = beforeDirtyNearest.source !== afterDirtyNearest.source && beforeDirtyLinear.source !== afterDirtyLinear.source; dirtyRegistry.destroy();
  const sampling = Object.freeze({ nearestSourceUid: nearest.texture.source.uid, linearSourceUid: linear.texture.source.uid, nearestMode: nearest.texture.source.scaleMode, linearMode: linear.texture.source.scaleMode, distinctSources: nearest.texture.source !== linear.texture.source, reverseResolutionStable: nearest.texture === nearestFirst && linear.texture === linearFirst, orderIndependent, dirtyRefreshIndependent }); const circlePixels = application.renderer.extract.pixels(gradientProbe).pixels; const circleColors = new Set<string>(); for (let index = 0; index < circlePixels.length; index += 4) { circleColors.add(`${circlePixels[index]},${circlePixels[index + 1]},${circlePixels[index + 2]},${circlePixels[index + 3]}`); } const gradientShapes = Object.freeze({ transformedRadialCircle: gradientCircle.alpha === .7 && gradientCircle.blendMode === "multiply", transformedRadialEllipse: gradientEllipse.alpha === .7 && gradientEllipse.blendMode === "multiply" && gradientEllipse.worldTransform.b !== gradientCircle.worldTransform.b, radialPixelsVary: circleColors.size > 2, transform: Object.freeze([gradientCircle.worldTransform.a, gradientCircle.worldTransform.b, gradientCircle.worldTransform.c, gradientCircle.worldTransform.d]) });
  const clippedLayer = new Container(); const clipContext = createSfhsPixiCanvasCompatContext(); clipContext.beginFrame(); clipContext.transform(1, 0, .2, 1, 10, 10); clipContext.beginPath(); clipContext.rect(0, 0, 40, 40); clipContext.clip(); clipContext.beginPath(); clipContext.rect(20, 0, 40, 40); clipContext.clip(); clipContext.setFont("700 12px system-ui"); clipContext.setTextBaseline("top"); clipContext.setTextAlign("center"); clipContext.fillText("CLIP", 30, 4); clipContext.fillRect(0, 0, 1, 1); const clipPresenter = createSfhsCompatClipPresenter(); const clippedState = clipContext.getCommands().at(-1)!.state; const clippedContent = clipPresenter.mount(clippedLayer, clippedState.clips); clippedContent.addChild(new Graphics().rect(0, 0, 80, 80).fill("#ffffff")); presentSfhsGradientRect(clippedLayer, clippedState, gradient, 0, 0, 80, 20, clipPresenter); const clippedText = presentSfhsText(clippedLayer, clipContext.getCommands().find((command) => command.operation === "fillText")!, clipPresenter); const clippedPixels = application.renderer.extract.pixels({ target: clippedLayer, frame: new Rectangle(0, 0, 80, 80) }); const alphaAt = (x: number, y: number) => clippedPixels.pixels[(y * clippedPixels.width + x) * 4 + 3] ?? 0; const clipIntersection = Object.freeze({ outsideLeft: alphaAt(20, 20) === 0, inside: alphaAt(40, 20) > 0, outsideRight: alphaAt(60, 20) === 0, textWeight: clippedText.style.fontWeight }); const clipBeforeRelease = clipPresenter.getDiagnostics(); clipPresenter.beginFrame(); const clipAfterRelease = clipPresenter.getDiagnostics(); const clipLifecycle = Object.freeze({ releasedEveryMask: clipAfterRelease.masksDestroyed === clipBeforeRelease.masksCreated, activeMasks: clipAfterRelease.activeMasks, activeScopes: clipAfterRelease.activeScopes }); clipPresenter.destroy(); clippedLayer.destroy({ children: true });
  application.renderer.resize(480, 270, 1); application.renderer.resize(320, 180, 1); application.render();
  Object.defineProperty(window, "CR", { value: Object.freeze({ snapshot: () => Object.freeze({ renderer: "PIXI", canvasCount: fixtureHost.querySelectorAll("canvas").length, canvasSize: Object.freeze({ width: application.canvas.width, height: application.canvas.height }), diagnostics: compat.getDiagnostics(), assets: assets.getDiagnostics(), assetLifecycle, unified: unified.getDiagnostics(), textures: registry.getDiagnostics(), sampling, gradientShapes, clipIntersection, clipLifecycle, compatibility: compatibilityDiagnostics.snapshot() }) }) });
}

void boot();
