import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildProject } from "@sfhs/builder";
import { describe, expect, it } from "vitest";
import type { CanvasCapabilityReport } from "@sfhs/canvas-capability-analyzer";
import { generateSfhsCanvasScaffold, SfhsScaffoldBlockedError, writeSfhsCanvasScaffold } from "./index.ts";
const report = { schema: "sfhs.canvas-capability-report@1", verdict: "ANALYSIS_PASS", unknownProductionPaths: [], operations: [{ operation: "arc", productionObserved: true, classification: "SUPPORTED_EXACT", pixiStrategy: "Pixi Graphics" }, { operation: "fillText", productionObserved: true, classification: "SUPPORTED_APPROXIMATION", pixiStrategy: "Pixi Text" }] } as unknown as CanvasCapabilityReport;
describe("Canvas scaffold generator", () => { it("creates a split fail-closed Pixi migration scaffold", () => { const result = generateSfhsCanvasScaffold({ projectId: "fixture", report, referenceStates: ["title", "win"] }); expect(result.verdict).toBe("MIGRATION_REQUIRED"); expect(result.files["src/main.ts"]).toContain("Canvas2D"); expect(result.files["evidence/migration-capabilities.json"]).toContain("fillText"); }); it("writes a buildable one-file-project source tree", async () => { const output = await mkdtemp(join(tmpdir(), "sfhs-012c-")); try { const scaffold = generateSfhsCanvasScaffold({ projectId: "fixture", report, referenceStates: ["title"] }); const written = await writeSfhsCanvasScaffold(output, scaffold); expect(written).toContain("sfhs.project.json"); expect(await readFile(join(output, "evidence", "migration-capabilities.json"), "utf8")).toContain("MIGRATION_REQUIRED"); expect((await buildProject(output)).javascript.length).toBeGreaterThan(0); } finally { await rm(output, { recursive: true, force: true }); } }); it("blocks incomplete analysis", () => { const blocked = { ...report, verdict: "BLOCKED_ON_UNSUPPORTED_CANVAS_FEATURES" } as CanvasCapabilityReport; expect(() => generateSfhsCanvasScaffold({ projectId: "x", report: blocked, referenceStates: [] })).toThrow(SfhsScaffoldBlockedError); }); });
